#!/bin/sh
#########################################################
#
#
#########################################################
## DRBD COMMON
#########################################################

if [ -f ../functions ] ; then
    . ../functions
else
    echo "! functions file needed! ; Exiting"
    exit 1
fi
if [ -f "${PWD}/nodes_ressources" ] ; then
    . ${PWD}/nodes_ressources
else
    echo "! functions file nodes_ressources needed! ; Exiting"
    exit 1
fi

check_load_config_file other

# SOME VARS
DRBDDEV="/dev/drbd0"
# by default DRBD
NODEA="${NODENAME}1"
NODEB="${NODENAME}2"
MNTTEST="/mnt/test"

install_packages_drbd() {
    echo $I "############ START install_packages_drbd" $O
    pssh -h /etc/hanodes "zypper in -y drbd-kmp-default drbd drbd-utils"
}

disable_drbd() {
    echo $I "############ START disable_drbd"
    echo "- Disable drbd service on node" $O
    exec_on_node ${NODEA} "systemctl disable drbd"
    exec_on_node ${NODEB} "systemctl disable drbd"
}

enable_drbd() {
    echo $I "############ START enable_drbd"
    echo "- Enable drbd service on node" $O
    exec_on_node ${NODEA} "systemctl enable drbd"
    exec_on_node ${NODEB} "systemctl enable drbd"
}

stop_drbd() {
    echo $I "############ START stop_drbd"
    echo "- Stop drbd service on node" $O
    exec_on_node ${NODEA} "systemctl stop drbd"
    exec_on_node ${NODEB} "systemctl stop drbd"
}

start_drbd() {
    echo $I "############ START start_drbd"
    echo "- Start drbd service on node" $O
    exec_on_node ${NODEA} "systemctl start drbd"
    exec_on_node ${NODEB} "systemctl start drbd"
}
