#!/bin/sh
#########################################################
#
#
#########################################################
## NODES RESSOURCES
#########################################################

if [ -f ../functions ] ; then
    . ../functions
else
    echo "! functions file needed! ; Exiting"
    exit 1
fi
check_load_config_file other

# SOME VARS
NODEA="${NODENAME}1"
NODEB="${NODENAME}2"
NODEC="${NODENAME}3"
MNTTEST="/mnt/test"
IPA=`grep ${NODEA} /var/lib/libvirt/dnsmasq/${NETWORKNAME}.hostsfile | cut -d , -f 2`
IPB=`grep ${NODEB} /var/lib/libvirt/dnsmasq/${NETWORKNAME}.hostsfile | cut -d , -f 2`


create_vol_name() {
    echo "############ START create_vol_name"
    if [ $# -ne 3 ]; then echo "- create_vol_name needs 3args: NODE / POOL_NAME / VOL_NAME" ; exit 1; fi
    NODE="$1"
    POOLNAME="$2"
    VOLNAME="$3"
    echo "- Create volume for device using ${POOLNAME} on ${NODE}"
    virsh vol-create-as --pool ${POOLNAME} --name ${VOLNAME}.qcow2 --format qcow2 --capacity 1G --allocation 1G --prealloc-metadata
    virsh vol-list ${POOLNAME} --details
    virsh pool-refresh --pool ${POOLNAME}
}

delete_vol_name() {
    if [ $# -ne 3 ]; then echo "- delete_vol_name needs 3args: NODE / POOL_NAME / VOL_NAME" ; exit 1; fi
    NODE="$1"
    POOLNAME="$2"
    VOLNAME="$3"
    echo "############ START delete_vol_name"
    echo "- Delete volume ${VOLNAME} ${POOLNAME} on ${NODE}"
    virsh vol-delete --pool ${POOLNAME} ${VOLNAME}.qcow2
}

delete_pool_name() {
    echo "############ START delete_pool_name"
    if [ $# -ne 1 ]; then echo "- delete_pool_name needs one arg: POOL_NAME" ; exit 1; fi
    POOLNAME="$1"
    echo "- Delete pool ${POOLNAME}"
    virsh pool-destroy ${POOLNAME}
    virsh pool-undefine ${POOLNAME}
    echo "- Delete path to volume"
    rm -rf ${STORAGEP}/${POOLNAME}
}

attach_disk_to_node() {
    echo "############ START attach_disk_to_node"
    NODE="$1"
    POOLNAME="$2"
    VOLNAME="$3"
    TARGETVD="$4"
    EXT="$5"
    if [ $# -ne 5 ]; then echo "- attach_disk_to_node needs 4args: NODE / POOL_NAME / VOL_NAME / TARGET VD / EXTENSION" ; exit 1; fi
    echo "- Attach volume ${POOLNAME} to ${NODE}, target is ${TARGETVD}"
    virsh attach-disk ${NODE} --live --cache none --type disk ${STORAGEP}/${POOLNAME}/${VOLNAME}.${EXT} --target ${TARGETVD}
    exec_on_node ${NODE} "fdisk -l /dev/${TARGETVD}"
}

check_targetvd_on_node() {
    echo "############ START check_targetvd_on_node"
    # workaround as this is not possible to garantee target device on VM guest
    if [ $# -ne 3 ]; then echo "- check_targetvd_on_node needs 3arg: NODE_NAME / TARGET_VD / START_LETTER" ; exit 1; fi
    NODE="$1"
    TARGETVD="$2"
    STARTLETTER="$3"
    exec_on_node ${NODE} "ls -la /dev/${TARGETVD}"
    if [ $? -eq 0 ]; then
	export REALTARGETVD=${TARGETVD}
    else
	for LETTER in {${STARTLETTER}..z}; do
	    #echo "- Testing /dev/vd${LETTER}"
	    export REALTARGETVD="vd${LETTER}"
	    exec_on_node ${NODE} "ls -la /dev/vd${LETTER}"
	    if [ $? -eq 0 ]; then
		#echo "- Switching target on HA node to vd${LETTER}"
		export REALTARGETVD="vd${LETTER}"
		break
	    #else
	    #echo "- Trying another letter..."
	    fi
	done
    fi
}

detach_disk_from_node() {
    echo "############ START detach_disk_from_node"
    if [ $# -ne 2 ]; then echo "- detach_disk_from_node needs 2args: NODE / DISK" ; exit 1; fi
    echo "- Detach disk ${TARGETVD} from ${NODE}"
    NODE="$1"
    TARGETVD="$2"
    echo "virsh detach-disk ${NODE} ${TARGETVD}"
    virsh detach-disk ${NODE} ${TARGETVD}
}


delete_cib_resource() {
    if [ $# -ne 3 ]; then echo "- delete_cib_resource needs 3args: NODE / CIBNAME / RESOURCEID" ; exit 1; fi
    NODE="$1"
    CIBNAME="$2"
    RESOURCEID="$3"
    echo "############ START delete_cib_resource"
    exec_on_node ${NODE} "crm cib list | grep ${CIBNAME}"
    if [ $? -eq 0 ]; then
        echo "- Deleting cib and resource ${RESOURCEID}"
        exec_on_node ${NODE} "crm<<EOF
resource stop ${RESOURCEID}
EOF"
echo "- Wait stop/clear/delete resource (10s)"
       sleep 10
       exec_on_node ${NODE} "crm<<EOF
resource clear ${RESOURCEID}
configure delete ${RESOURCEID}
cib delete ${CIBNAME}
verify
configure commit
exit
EOF"
    else
        echo "- cib ${CIBNAME} doesnt exist "
    fi
    echo "- Show status"
    exec_on_node ${NODE} "crm status"
}

