#!/bin/sh
# execute a command on a NODE
exec_on_node() {
    # first arg is NODE name, second arg is command
    if [ $# -lt 2 ]
    then
	echo "! Two args needed (NODE CMD); Exiting"
        exit 1
    fi
    NODE="$1"
    CMD="$2"
    # avoid: No pseudo-tty detected! Use -t option to ssh if calling remotely
    echo "${NODE}: ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${NODE} ${CMD}"
    ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${NODE} ${CMD}
}

