#!/bin/sh
# execute a command on a NODE

check_config_file() {
if [ -f `pwd`/haqasemi.conf ]; then
    source `pwd`/haqasemi.conf
else
    echo "!! haqasemi.conf not found in current path !!"
    exit 1
fi
}

exec_on_node() {
    # first arg is NODE name, second arg is command
    if [ $# -lt 2 ]
    then
	echo "! Two args needed (NODE CMD); Exiting"
        exit 1
    fi
    NODE="$1"
    CMD="$2"
    # avoid: No pseudo-tty detected! Use -t option to ssh if calling remotely
    echo "${NODE}: ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${NODE} ${CMD}"
    ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${NODE} ${CMD}
}

scp_on_node() {
    # first arg is NODE name, second arg is SOURCE file, last arg is destination dir
    if [ $# -lt 3 ]
    then
	echo "! 3 args needed (NODE FILE DEST); Exiting"
        exit 1
    fi
    NODE="$1"
    FILE="$2"
    DEST="$3"
    # avoid: No pseudo-tty detected! Use -t option to ssh if calling remotely
    echo "${NODE}: scp -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${NODE} ${FILE} ${NODE}:${DEST}"
    ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${FILE} ${NODE}:${DEST}
}


create_pool() {
	POOL=$1
    echo "############ START create a pool ${POOL} #############"
    virsh pool-list --all | grep ${POOL} > /dev/null
    if [ $? == "1" ]; then
        echo "- ${POOL} not present, will create one"
        mkdir ${STORAGEP}/${POOL}
        virsh pool-define-as --name ${POOL} --type dir --target ${STORAGEP}/${POOL}
        virsh pool-start ${POOL}
        virsh pool-autostart ${POOL}
    else
        echo "- ${POOL} already present, skipping"
    fi
}

